In [1]:
import numpy as np

In [18]:
x = np.ones(10,dtype = 'int16')
x

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int16)

In [19]:
# reshape to a matrix with 2 rows and 5 columns
x = x.reshape(2,5)
x

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]], dtype=int16)

In [20]:
np.pad(x, 3)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0],
       [0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]], dtype=int16)

 __pad_width__ : {sequence, array_like, int}
        Number of values padded to the edges of each axis.
        ((before_1, after_1), ... (before_N, after_N)) unique pad widths
        for each axis.
        ((before, after),) yields same before and after pad for each axis.
        (pad,) or int is a shortcut for before = after = pad width for all
        axes.
        
* before == left and top sides
* after == right and bottom sides

In [22]:
# pad the matrix with a width of 1 on the top and left sides and with a width of 3 on the bottom and right sides
np.pad(x, pad_width=(1,3))

array([[0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 1, 1, 1, 1, 0, 0, 0],
       [0, 1, 1, 1, 1, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0]], dtype=int16)

In [23]:
# pad the matrix with a width of 3 on the top and left sides 
# and with a width of 0 on the bottom and right sides
# this will also put the original matrix into the bottom right corner
np.pad(x, pad_width=(3,0))

array([[0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 1, 1, 1, 1],
       [0, 0, 0, 1, 1, 1, 1, 1]], dtype=int16)

In [30]:
# put the array on the top left corner
np.pad(x,(0,3))

array([[1, 1, 1, 1, 1, 0, 0, 0],
       [1, 1, 1, 1, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0]], dtype=int16)

# Padding different axes

__pad_width__ = (before,after)
Before is the pad width before you see the values of the vector/matrix your padding. 
For example, if I have the array
```python
                                                                [2,4,6] 
```
and my before pad width is (2,0), my new array will look like
```python
                                                                [0,0,2,4,6] 
```
This is because a vector only has 1 dimension so when its padded it will only pad along that 1 dimension, and since we only specified it to pad __before__ we end up with two 0's at the begining of
the vector. 

If i were to put a value in the after spot, say (2,2), the vector would look like:
```python
                                                                [0,0,2,4,6,0,0]
```
Likewise if I had a 2d matrix with the values
```python
                                                                [[2,4,6]
                                                                 [1,3,5]]
```
and use the same padding (2,0) my new matrix will look like 
```python
                                                                [[... 0,0,0]
                                                                 [... 0,0,0]
                                                                 [0,0,2,4,6]
                                                                 [0,0,1,3,5]]
```
Because we're now padding in two dimensions, we add 2 rows of zeros on top of [2,4,6], and two columns of zeros before [2,1].  

I can specify which axis to pad on by using this syntax:
```python
   np.pad(  data = vector/matrix, pad_width = ( (before_0,after_0), (before_1,after_1), ...(before_n,after_n) )  )
```
Where the number corresponds to the axis
* 0 = rows (padding on the top and the bottom)
* 1 = columns (padding on the left and right sides)
* n = can go up to however many dimensions your data has

Following these rules,

say I want to before pad the columns of my matrix by 2 without any row padding. I can use a pad width of (0,0) to not add any padding along axis 0, and (2,0) to add a padding of 2 along axis 1.
```python
                                                                pad_width = ((0,0),(2,0))
                                                                0 ->    
                                                              1 [[0,0,2,4,6]       
                                                              |  [0,0,1,3,5]]
                                                              v
```
If I wanted to switch it to add padding along the rows and not the columns I would change it to
```python
                                                                pad_width = ((2,0),(0,0))
                                                                [[0,0,0]
                                                                 [0,0,0]
                                                                 [2,4,6]
                                                                 [1,3,5]]
```
Adding a value to the __after__ variable will do the same thing but on the opposite side
```python
                                                                pad_width = ((2,2),(0,0))
                                                                [[0,0,0]
                                                                 [0,0,0]
                                                                 [2,4,6]
                                                                 [1,3,5]
                                                                 [0,0,0]
                                                                 [0,0,0]]
```

### More padding examples and their outputs
```python

x = [[1,2,3]
     [4,5,6]]

pad_width = (2) 

      [[0, 0, 0, 0, 0, 0, 0],            rows         columns
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 2, 3, 0, 0],       -> before_0 = 2, before_1 = 2        
       [0, 0, 4, 5, 6, 0, 0],       -> after_0  = 2, after_1  = 2
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0]]
  
''' in plain text: 
        - add 2 rows of padding before and after
        - add 2 columns of padding before and after.'''
    
    
    
pad_width = (2,0)

      [[ ...  0, 0, 0],                  rows         columns
       [ ...  0, 0, 0],             -> before_0 = 2, before_1 = 2
       [0, 0, 1, 2, 3],             -> after_0  = 0, after_1  = 0
       [0, 0, 4, 5, 6]]

''' in plain text: 
        - add 2 rows of padding before
        - add 2 columns of padding before.'''
    
pad_width = ((1,0),(4,2))

      [[ .......... 0, 0, 0, 0, 0],      rows          columns
       [0, 0, 0, 0, 1, 2, 3, 0, 0],  -> before_0 = 1, before_1 = 4
       [0, 0, 0, 0, 4, 5, 6, 0, 0]]  -> after_0  = 0, after_1  = 2
    
''' in plain text: 
        - add 1 row of padding before
        - add 4 columns of padding before and 2 columns after.'''
```

In [28]:

np.pad(x, pad_width = ((0,0),(3,1)))

array([[0, 0, 0, 1, 1, 1, 1, 1, 0],
       [0, 0, 0, 1, 1, 1, 1, 1, 0]], dtype=int16)

In [31]:
np.pad(x, pad_width = ((1,0),(3,1)))

array([[0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 1, 1, 1, 1, 0],
       [0, 0, 0, 1, 1, 1, 1, 1, 0]], dtype=int16)

In [60]:
np.pad([[1,2,3],[4,5,6]],pad_width = ((1,0),(4,2)))

array([[0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 2, 3, 0, 0],
       [0, 0, 0, 0, 4, 5, 6, 0, 0]])

In [69]:
x = np.array([1,2,3])
print(x)
print(x.shape)
x = np.expand_dims(x,axis = 0)
print(x)
print(x.shape)
x = np.expand_dims(x,axis = 0)
print(x)
print(x.shape)

[1 2 3]
(3,)
[[1 2 3]]
(1, 3)
[[[1 2 3]]]
(1, 1, 3)
